name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_mode:
        description: Build type for Buildozer
        required: true
        default: debug
        type: choice
        options:
          - debug
          - release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILDOZER_WARN_ON_ROOT: "0"
      APP_ANDROID_ARCH: arm64-v8a

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build arm64-v8a APK
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: ${{ github.event_name == 'workflow_dispatch' && format('buildozer android {0}', inputs.build_mode) || 'buildozer android debug' }}
          buildozer_version: stable

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ETGmusic-${{ github.event_name == 'workflow_dispatch' && inputs.build_mode || 'debug' }}-arm64-v8a
          path: ${{ steps.buildozer.outputs.filename }}
          if-no-files-found: error
